engines:
  eslint:
    channel: eslint-3
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- dist/*
- src/migrations/*
- /**/*.spec.js
- coverage/**/*
- node_modules/**/*